### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by Butonix** [eugenezadorin/node-telegraph#1]
Hi
How to edit text?

**Comment by eugenezadorin** [comment]
About the original question — I added an installation guide to readme.

Demo-content removed from main page. Now there is three contenteditable blocks — title, author and story.

**Comment by Butonix** [comment]
Look
how to add a button to edit after publication, as in a telegra.ph? (http://prntscr.com/hlmtms)
and the most important button is adding video and images both to the telegra.ph (http://prntscr.com/hlmtbu)
Also save the text after reloading the page

**Comment by eugenezadorin** [comment]
All these features are planned and will be released soon.

**Comment by Butonix** [comment]
I'm sorry, will you add the ability to insert links, video photos and so on????
https://prnt.sc/hlmtbu

**Comment by eugenezadorin** [comment]
Sure, video and image buttons will be added into the toolbar. I'm working on the toolbar and server-side code.

You already can insert links, code blocks, headers and quotes in the latest version: https://prnt.sc/hqpcjg

Note that the appearance of the link inserting block will be improved.

**Comment by Butonix** [comment]
Error: Request failed with status code 413
    at t.exports (http://localhost:3000/js/bundle.js:7:217621)
    at t.exports (http://localhost:3000/js/bundle.js:19:1212)
    at XMLHttpRequest.d.(anonymous function) (http://localhost:3000/js/bundle.js:7:216622)

**Comment by eugenezadorin** [comment]
Need more information, what action did you take?
I've been added sourcemapping, perhaps it will help more accurately identify the error

**Comment by Butonix** [comment]
This happens when I add a photo from my computer.
I added, I save the save and nothing happens, in the console such errors

Failed to load resource: the server responded with a status of 413 (Payload Too Large)
bundle.js:19 Error: Request failed with status code 413
    at t.exports (http://localhost:3000/js/bundle.js:7:217621)
    at t.exports (http://localhost:3000/js/bundle.js:19:1212)
    at XMLHttpRequest.d.(anonymous function) (http://localhost:3000/js/bundle.js:7:216622)

**Comment by eugenezadorin** [comment]
Just pushed big update into master branch. Images now stores on server as files, not as base64-strings in editor. Check it out, I think your problem is probably solved.

**Comment by Butonix** [comment]
npm run server

> node-telegraph@1.0.0 server C:\Users\rever\Desktop\node-telegraph-master
> nodemon server.js

[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
module.js:538
    throw err;
    ^

Error: Cannot find module 'mmmagic'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\rever\Desktop\node-telegraph-master\server\app.js:6:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by eugenezadorin** [comment]
You should install missing dependencies with `npm install`. It may cause problems with C++ libraries. See readme file for more info.
